---
- hosts: ubuntu
  roles:
    - webserver

  handlers:
    - name: restart apache
      service: 
        name: apache2
        state: restarted



#- hosts: ubuntu
#  tasks:
#   - name: install apache2 and other multiple packages.(as a loop over multiple items)
#      apt: name=apache2 state=present
#      with_items:
#       - apache2
#       - libapache2-mod-wsgi 
#       - python-pip
#       - python-virtualenv 
#


 
#- hosts: ubuntu
#  tasks:
#   - name: install apache2 and other multiple packages.(as a loop over multiple items)
#      apt: name={{item}} state=present
#      with_items:
#       - apache2
#       - libapache2-mod-wsgi 
#       - python-pip
#       - python-virtualenv 
