---
# tasks file for webserver
- name: install apache and modules
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - apache2 
   - libapache2-mod-wsgi
   - python-pip
   - python-virtualenv
- name: start apache
  service: 
   name: apache2
   state: started
   enabled: yes

- name: enable mod_wsgi
  apache2_module:
   state: present
   name: wsgi
   notify: restart apache    

