---
- hosts: lb
  become: true
  tasks: 
    - name: install nginx
      apt: name=nginx state=present update_cache=yes
    - name: start nginx
      service: name=nginx state=started enabled=yes
    - name: conf
      template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify: restart nginx
    - name: deactivate default conf
      file: path=/etc/nginx/sites-enabled/default state=absent 
    - name: activate new conf
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted    
